### ISSUE TITLE
Couldn't get access to dataset

### ISSUE THREAD

**Issue by FlappypigJohn** [rpp0/em-operation-extraction#1]
It seems http://wisecdata.ccs.neu.edu/ only have three years' dataset, i couldn't find the dataset refered in the paper. Hope you can help me out.

**Comment by rpp0** [comment]
Hi! We're still waiting on the WiSec staff for the official upload. However, here's a direct link to the VM in the meantime: https://drive.google.com/file/d/1GBBbPCVjozUGhXLmyXx67skNjFHExM_e/view?usp=sharing

**Comment by FlappypigJohn** [comment]
> Hi! We're still waiting on the WiSec staff for the official upload. However, here's a direct link to the VM in the meantime: https://drive.google.com/file/d/1GBBbPCVjozUGhXLmyXx67skNjFHExM_e/view?usp=sharing

Thanks for yur help :D
